// <auto-generated />
namespace Infinite.OnlineStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Intial_Database : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Intial_Database));
        
        string IMigrationMetadata.Id
        {
            get { return "202301221550562_Intial_Database"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
